name: cd

on:
  push:
    branches:
      - dev

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Using ssh
        uses: goldyTW/majja@dev
        with:
          host: 203.161.53.80
          username: root
          password: Majj@clinic2023
          port: 22
          script: |
            cd ~/frontend/dev/majja
            git pull origin dev
            git status
            sudo docker rm frontend_container_dev -f
            sudo docker rmi frontend_dev
            sudo docker build . --no-cache -t frontend_dev
            sudo systemctl stop docker
            sudo systemctl start docker